http:
  host: "0.0.0.0"
  port: "8090"
  readTimeout: "5s"
  writeTimeout: "5s"
  maxHeaderBytes: 1048576

kafka:
  producer:
    brokers: ["localhost:29092"]
    topic: "segmentation"
    requiredAcks: -1
    retryMax: 5
    returnSuccess: true
  consumer:
    brokers: ["localhost:29092"]
    topic: "segmentation"
    autoOffsetReset: -1
    returnErrors: true

segment:
  maxSegmentSize: 100
  assemblyPeriod: "2s"