http:
  host: "192.168.204.224"
  port: "8000"
  readTimeout: "5s"
  writeTimeout: "5s"
  maxHeaderBytes: 1048576

httpClient:
  codeURL: "http://192.168.204.34:3050/api/code"
  receiveURL: "http://192.168.204.224:8010/api/receive"

kafka:
  producer:
    brokers: [ "localhost:29092" ]
    topic: "segmentation"
    requiredAcks: -1
    retryMax: 5
    returnSuccess: true
  consumer:
    brokers: [ "localhost:29092" ]
    topic: "segmentation"
    autoOffsetReset: -1
    returnErrors: true

segment:
  maxSegmentSize: 100
  assemblyPeriod: "2s"